//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipArchiveNormalizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(?!.*青空文庫txt).*\\.zip$")]
        public string ImageCollectionArchiveFileNamePatternText {
            get {
                return ((string)(this["ImageCollectionArchiveFileNamePatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("青空文庫txt.*\\.zip$")]
        public string AozoraBunkoArchiveFileNamePatternText {
            get {
                return ((string)(this["AozoraBunkoArchiveFileNamePatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^((?!.*青空文庫txt).*\\.zip)|(.*\\.epub)$")]
        public string ContentArchiveFileNamePatternText {
            get {
                return ((string)(this["ContentArchiveFileNamePatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\\.(pdf|bmp|zip)$)|(resized)")]
        public string NotedEntryNamePatternText {
            get {
                return ((string)(this["NotedEntryNamePatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^mimetype$")]
        public string MimeTypeEntryNamePatternText {
            get {
                return ((string)(this["MimeTypeEntryNamePatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(.*\\.(exe|bat|scr|com|vbs|jar|db|ini|url|lst|dvi|htm|html|mht|mhtml|rtf|txt)|\\.D" +
            "S_Store)$")]
        public string UselessEntryNameForImageCollectionPatternText {
            get {
                return ((string)(this["UselessEntryNameForImageCollectionPatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(.*\\.(exe|bat|scr|com|vbs|jar|db|ini|url|lst|dvi|htm|html|mht|mhtml|rtf)|\\.DS_St" +
            "ore)$")]
        public string UselessEntryNameForAozoraBunkoPatternText {
            get {
                return ((string)(this["UselessEntryNameForAozoraBunkoPatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\.(exe|bat|scr|com|vbs|jar)$")]
        public string UselessEntryNameForContentPatternText {
            get {
                return ((string)(this["UselessEntryNameForContentPatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(read ?me\'?|誤字脱字|置換|訂正リスト|追記|注|校正情報|おまけ|注意)(\\s*\\((unicode|utf-?(7|8|16|31))\\))?$" +
            "")]
        public string FilesNotToBeExtractedForAozoraBunkoPatternText {
            get {
                return ((string)(this["FilesNotToBeExtractedForAozoraBunkoPatternText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZipArchiveNormalizer")]
        public string ApplicationName {
            get {
                return ((string)(this["ApplicationName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0E8080EB;E159561F")]
        public string NotedEntryCrc32List {
            get {
                return ((string)(this["NotedEntryCrc32List"]));
            }
        }
    }
}
